name: github actions on PR to master

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-24.04
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.12.4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.3.0
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.12.4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.3.0
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
