name: github actions on PR to master

on:
  push:
    branches:
      - issues/43

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run tests
        run: |
          nix develop -c sh -lc 'pnpm install --frozen-lockfile && pnpm run test'

  storybook-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run storybook tests
        run: |
          nix develop -c sh -lc 'pnpm install --frozen-lockfile && pnpm run test:storybook:ci'

  # build:
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: cachix/install-nix-action@v27
  #       with:
  #         extra_nix_config: |
  #           experimental-features = nix-command flakes

  #     - name: Build
  #       run: |
  #         nix develop -c sh -lc 'pnpm install --frozen-lockfile && pnpm run build'
