name: github actions on release push

on:
  push:
    branches:
      - release

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build
        run: |
          nix develop -c sh -lc 'pnpm install --frozen-lockfile && pnpm run build'

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - uses: actions/deploy-pages@v4
